#!/bin/bash
#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# STOP SYSTEMD SERVICE
#=================================================
# ynh_script_progression "Stopping $app's systemd service..."

# ynh_systemctl --service="$app" --action="stop"

#=================================================
# Migrate
#=================================================

if [ -f "/etc/cron.d/$app" ]; then
    ynh_safe_rm "/etc/cron.d/$app"
fi

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Upgrading source files..."

_git_clone_or_pull "$install_dir/appstore"
_git_clone_or_pull "$install_dir/apps" https://github.com/YunoHost/apps.git
_git_clone_or_pull "$install_dir/apps_tools" https://github.com/YunoHost/apps-tools.git

ynh_config_add --template="update_catalog.sh" --destination="$install_dir/update_catalog.sh"
chmod +x "$install_dir/update_catalog.sh"

ynh_config_add --template="update_catalog_notify.sh" --destination="$install_dir/update_catalog_notify.sh"
chmod +x "$install_dir/update_catalog_notify.sh"

# Fixture until we manage it properly
# ln -s "$install_dir/apps" "$install_dir/appstore/.cache/apps"
# ln -s "$install_dir/apps_cache" "$install_dir/appstore/.apps_cache"

# That way, we keep the www-data group when creating files
chmod g+s "$install_dir/appstore/assets"

chown -R "$app:www-data" "$install_dir"

mkdir -p "$data_dir/appstore_data"
chown "$app:$app" "$data_dir/appstore_data"

#=================================================
# INSTALL APP
#=================================================
ynh_script_progression "Upgrading app..." --weight=5

pushd "$install_dir/apps_tools" > /dev/null
{
    _update_venv
    ynh_exec_as_app venv/bin/pip install -r requirements.txt > /dev/null
}
popd > /dev/null

ynh_script_progression "Downloading apps and appstore cache..."
# Actually just start the service to prevent a downtime
# ynh_exec_as_app "$install_dir/update_catalog.sh"
chown -R "$app:www-data" "$install_dir/appstore/assets"

#=================================================
# REAPPLY SYSTEM CONFIGURATIONS
#=================================================
ynh_script_progression "Upgrading system configurations related to $app..."

ynh_config_add_nginx

ynh_config_add --template="systemd-update.service" --destination="/etc/systemd/system/$app-update.service"
ynh_config_add --template="systemd-update.timer" --destination="/etc/systemd/system/$app-update.timer"
ynh_config_add_systemd
systemctl enable "$app-update.timer" --now --quiet

yunohost service add "$app" --log="/var/log/$app/$app.log"

ynh_config_add_logrotate

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression "Starting $app's systemd service..."

ynh_systemctl --service="$app" --action="restart"
ynh_systemctl --service="$app-update" --action="start"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Upgrade of $app completed"
